### ISSUE TITLE
AutoRenewTimeout?

### ISSUE THREAD

**Issue by pberggreen** [cmendible/AzureBus#1]
How do I set AutoRenewTimeout? 
I thought that I could use WithSubscriptionConfiguration, but ISubscriptionConfiguration does not have AutoRenewTimeout.

**Comment by cmendible** [comment]
Hi sorry about that! The property indeed is missing. 

Are you using AzureBus or AzureBus.ForWindowsServer? The reaso i ask is becuase I'm planning to port the project to support .NET Standarad and I´m not sure if I'll dump support for Service Bus for Windows Server.

**Comment by pberggreen** [comment]
I'm using AzureBus.
I tried setting AutoRenewTimeout manually, but I got a compiler error because this property isn't supported by ServiceBus for WindowsServer.

**Comment by cmendible** [comment]
Ok. I'm planning to add AutoRenewTimeout over the weekend.

**Comment by cmendible** [comment]
Hi, just released version v1.0.1.4. You can check the changes [here](https://github.com/cmendible/AzureBus/commit/f656e0dea0c39e92326c67a3417507c29e78c3a3) and the nuget package [here](https://www.nuget.org/packages/AzureBus/)

Hope it helps!
